### ISSUE TITLE
Help building examples - text elements don't use the right font

### ISSUE THREAD

**Issue by chrisdiamand** [OpenLilyPondFonts/lilyjazz#6]
Hi!

I've been trying to build the lilyjazz examples:
```
# cd lilyjazz/examples
# lilypond -I../stylesheet -I../otf AllOfMe.ly
GNU LilyPond 2.20.0
Processing `AllOfMe.ly'
Parsing...
Interpreting music...[8][16][24][32][40]
Preprocessing graphical objects...
Interpreting music...
MIDI output to `AllOfMe.midi'...
Interpreting music...
Preprocessing graphical objects...
Calculating line breaks... 
Drawing systems... 
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Layout output to `/tmp/lilypond-yoeHeS'...
Converting to `AllOfMe.pdf'...
Deleting `/tmp/lilypond-yoeHeS'...
Success: compilation successfully completed
```
The notes on the stave are using the lilyjazz font and look great, but all of the text elements (title, composer, lyrics etc) seem to be stuck using the default font. Here's the output: [AllOfMe.pdf](https://github.com/OpenLilyPondFonts/lilyjazz/files/5757724/AllOfMe.pdf)

Have I missed something? Thanks!

**Comment by chrisdiamand** [comment]
...and fixed! Sorry for the noise.

The issue was that I hadn't installed `lilyjazz-chord.otf` or `lilyjazz-text.otf`. Adding the `-I` flags to the `lilypond` invocation was enough to tell it where to find the `lilyjazz` font for `#:music`, but for the text elements I guess it must delegate to Fontconfig, which doesn't error when it can't find a font - it just silently returns the wrong one.

So the fix was to do:
```
# cd lilyjazz
# cp supplementary-files/lilyjazz-chord/lilyjazz-chord.otf supplementary-files/lilyjazz-text/lilyjazz-text.otf ~/.local/share/fonts
# cd examples
# lilypond -I../stylesheet -I../otf AllOfMe.ly
```

**Comment by jackmcrider** [comment]
I had the same problem, but wanted a solution that works with Frescobaldi and found this: https://lists.gnu.org/archive/html/lilypond-user/2016-04/msg00286.html

> i manually moved all fonts (including lilyjazz-text.otf and lilyjazz-chord.otf) from /Users/…/Library/Fonts to /Library/Fonts
